### ISSUE TITLE
radio diagnostics page enhancements (SID/RSSI/packets info onscreen)

### ISSUE THREAD

**Issue by nanometrenat** [servalproject/lbard#10]
http://192.168.3.1:21506

1) please add device SID on this screen too ("Hi I am...") so that one doesn't need to flick back to the wifi diagnostics each time, and so screenshots show the device I'm looking at as well as the traffic to/from other devices.
2) traffic info:  add a list of recently received packets and which peers it thinks already has them
3) add RSSI for latest timestamp AND the RSSI for the latest n packets received.  This is useful for situations where radio connectivity is intermittent.

**Comment by gardners** [comment]
This should also include information on the status of the radio, i.e., time since last heart-beat, and the model of radio detected, so that non-flashed or faulty radios can be more easily detected.

**Comment by gardners** [comment]
Point 1. of original report has been addressed by the above commits.

**Comment by gardners** [comment]
Item 3 is now functional following commit bb438d9a, although it isn't perfect.
The RSSI shows activity for the past 1 minute for each peer that we have received a packet from lately.
Together with the various bug fixes for bundle transfer, item 2 is not required. If the situation changes, a new issue can be created.
