### ISSUE TITLE
LBARD status message doesn't update sometimes when few packets arriving?

### ISSUE THREAD

**Issue by stimbert** [servalproject/lbard#20]
The LBARD status message (and the /tmp/networkstatus.html) doesn't always update when few packets arriving.
This could happened because of time going backward.

**Comment by gardners** [comment]
Some recent commits have addressed some edge cases for time going backwards.
Time reversal is not currently supported in the test framework, as this requires modifying the operating system's sense of the current time.  Thus confirmation currently requires using real mesh extenders, or seeing if Lars etc from Marburg can help us setup the QEMU simulation framework. In either case, we will need to set up nodes with differing clocks, and seeing if we can reproduce the problem, and deriving a test case from that.  It might also be possible to have LBARD support a "virtual clock" to allow testing in the existing test framework.

**Comment by gardners** [comment]
Confirming that this happens with HTTP server still live and responding to queries.

**Comment by gardners** [comment]
Issue is actually caused by time running backwards.

**Comment by gardners** [comment]
Various time flow fixes have been put in place, that should correct this and some other issues, subject to testing.
