### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by nachtmaar** [servalproject/lbard#3]
Hi,

I installed lbard and serval-dna.
Unfortunately, the tests fail for me.

```
1 [FAIL.] A single bundle transfers to peers
2 [FAIL.] All peers receive bundles from all other peers
2 tests, 0 pass, 2 fail, 0 error
```

Can you confirm that the tests are failing? Or am I doing something wrong?

**Comment by gardners** [comment]
Hello,

Please attach the test logs for the failing tests.

Paul.

**Comment by nachtmaar** [comment]
Here are the test logs:

[1.One.FAIL.txt](https://github.com/servalproject/lbard/files/346020/log.txt)
[2.All.Fail](https://github.com/servalproject/lbard/files/346021/log.txt)

Let me know if you need more!

**Comment by gardners** [comment]
Hello,

Okay, so the fake radio is sending and receiving packets, but possibly is
stuffing something up, as lbard on one side is seeing very suspicious
things, e.g., where it sees some crazy peers being registered.

What OS are you running this on?

Meanwhile, try adding one or more of the diagnostic debug outputs to the
lbard command line, e.g., "announce", "radio" and/or "pieces".  This will
increase the volume of output from lbard in hopefully helpful ways, to work
out whether lbard is misinterpreting packets, or whether fakecsmaradio is
giving it corrupted packets.

Paul.

**Comment by nachtmaar** [comment]
I am using Ubuntu 16.04 LTS in a VM.

I also tested it on Ubuntu 14.04 LTS.

I added "radio" and "pieces" as lbard option like this:

tests/lbard:
```
   fork %lbardA lbard "$addr_localhost:$PORTA" lbard:lbard "$SIDA" "$tty1" announce pull
   fork %lbardB lbard "$addr_localhost:$PORTB" lbard:lbard "$SIDB" "$tty2" radio pull
   fork %lbardC lbard "$addr_localhost:$PORTC" lbard:lbard "$SIDC" "$tty3" pieces pull
   fork %lbardD lbard "$addr_localhost:$PORTD" lbard:lbard "$SIDD" "$tty4" pull
```
I recognized that test2 only fails sometimes, therefore I appended the log files from the 2 tests:


Test Run #1: both tests failed
[1.One.Fail](https://github.com/servalproject/lbard/files/347983/log.txt)
[2.All.FAIL](https://github.com/servalproject/lbard/files/347985/log.txt)

Test Run #2: second test passed
[1.One.Fail](https://github.com/servalproject/lbard/files/347988/log.txt)
[2.All.FAIL](https://github.com/servalproject/lbard/files/347986/log.txt)

**Comment by gardners** [comment]
Thanks. I'll try to take a look as soon as I am able to.

Paul.

**Comment by nachtmaar** [comment]
Hi, any news?

**Comment by gardners** [comment]
Hello,

Unfortunately I have been flat out lately.  I am not currently sure when I
will be able to attend to this, as the coming few weeks are also quite busy
for me.  If you can please ensure that it is logged as an issue against the
lbard github repository, that will help ensure that it gets attended to.

You may wish to try using the latest version of lbard, to confirm if it
still occurs, as there has been some development work on lbard since then.

Paul.

**Comment by gardners** [comment]
Sorry for the radio silence. We are actively working on some fixes for a number of internally detected problems in lbard.  Will update when results are in.

**Comment by gardners** [comment]
Confirming that most of the preliminary tests are passing again with the head of MeshExtender2.0 branch.  We will look into the remaining failing tests once I am back in Australia.

**Comment by gardners** [comment]
Confirming that tests now pass on MeshExtender2.0 branch at commit 93ee0d27a5a09a9ad8fde76eb61f3408268118b9:

1 [PASS.] LBARD detects RFD900 radios
2 [PASS.] LBARD detects Codan HF Radios
3 [PASS.] LBARD detects Barrett HF radios
4 [PASS.] A single very small bundle transfers to a single peer
5 [PASS.] A single very small bundle transfers to 3 peers
6 [PASS.] A single very small bundle transfers to 19 peers
7 [PASS.] A single 2KB bundle transfers to peers
8 [PASS.] A single bundle is offered by two senders
9 [PASS.] A bundle can be received by combining pieces from different senders
10 [PASS.] Ten receivers receive 6KB bundle from 10 senders in <2 minutes
11 [PASS.] One receiver receives a 16KB bundle from 19 senders in <2 minutes
12 [PASS.] All peers receive bundles from all other peers
13 [PASS.] Send messages, ack and read them in a 2 party conversation via UHF
14 [PASS.] Two party MeshMS conversation via UHF with 75% packet loss
15 [PASS.] MeshMS conversation via UHF with other bundles held and 25% packet loss
16 [PASS.] MeshMS conversation via UHF with other bundles in flight and 25% packet loss
17 [PASS.] MeshMS conversation via UHF, via two intermediate UHF hops
18 [PASS.] 5K file delivery, via two intermediate UHF hops
19 [PASS.] 5K file delivery, via two intermediate UHF hops, disable all improvements
20 [PASS.] Ten receivers receive 6KB bundle from 10 senders, disable randomise redirect offset
21 [PASS.] Ten receivers receive 6KB bundle from 10 senders, disable randomise start offset
22 [PASS.] Ten receivers receive 6KB bundle from 10 senders, disable randomise start and redirect offsets
23 [PASS.] Ten receivers receive 6KB bundle from 10 senders, disable bitmap tranfsers
24 [PASS.] Ten receivers receive 6KB bundle from 10 senders, disable bitmap transfers and randomised redirection
25 [PASS.] Ten receivers receive 6KB bundle from 10 senders, disable bitmap transfers and randomised start offsets
26 [PASS.] Ten receivers receive 6KB bundle from 10 senders, disable bitmap transfers and randomised start and redirection offsets
27 [PASS.] Ten receivers receive 6KB bundle from 10 senders, disable hard lower bound advancing
28 [PASS.] Ten receivers receive 6KB bundle from 10 senders, disable hard lower bound advancing and randomisation of redirection offset
29 [PASS.] Ten receivers receive 6KB bundle from 10 senders, disable hard lower bound advancing and randomisation of start offset
30 [.....] Ten receivers receive 6KB bundle from 10 senders, disable hard lower bound advancing and randomisation of start and redirection off30 [PASS.] Ten receivers receive 6KB bundle from 10 senders, disable hard lower bound advancing and randomisation of start and redirection offsets
31 [PASS.] Ten receivers receive 6KB bundle from 10 senders, disable hard lower bound advancing and bitmap transfers
32 [.....] Ten receivers receive 6KB bundle from 10 senders, disable hard lower bound advancing, bitmap transfers and randomisation of redirec32 [PASS.] Ten receivers receive 6KB bundle from 10 senders, disable hard lower bound advancing, bitmap transfers and randomisation of redirection offset
33 [.....] Ten receivers receive 6KB bundle from 10 senders, disable hard lower bound advancing, bitmap transfers and randomisation of start o33 [PASS.] Ten receivers receive 6KB bundle from 10 senders, disable hard lower bound advancing, bitmap transfers and randomisation of start offset
34 [PASS.] Ten receivers receive 6KB bundle from 10 senders, disable all improvements
35 [PASS.] Ten receivers and ten senders, 5 packets each per 4 seconds
36 [PASS.] Ten receivers and ten senders, 10 packets each per 4 seconds
37 [PASS.] Ten receivers and ten senders, 15 packets each per 4 seconds
38 [PASS.] Ten receivers and ten senders, 20 packets each per 4 seconds
39 [PASS.] Ten receivers and ten senders, 25 packets each per 4 seconds
40 [PASS.] Ten receivers and ten senders, 30 packets each per 4 seconds
41 [PASS.] Ten receivers and ten senders, 40 packets each per 4 seconds
42 [PASS.] Ten receivers and ten senders, 50 packets each per 4 seconds
43 [PASS.] Ten receivers and ten senders, 60 packets each per 4 seconds
44 [PASS.] Ten receivers and ten senders, 70 packets each per 4 seconds
45 [PASS.] Ten receivers and ten senders, 80 packets each per 4 seconds
46 [PASS.] Ten receivers and ten senders, 90 packets each per 4 seconds
47 [PASS.] Ten receivers and ten senders, 100 packets each per 4 seconds
48 [PASS.] Ten receivers and ten senders, 110 packets each per 4 seconds
49 [PASS.] Ten receivers and ten senders, 200 packets each per 4 seconds
49 tests, 49 pass, 0 fail, 0 error
