### ISSUE TITLE
LBARD log file needs to behave correctly when time goes backwards

### ISSUE THREAD

**Issue by nanometrenat** [servalproject/lbard#5]
Improved logging has been implemented, however further improvements are required.

Currently the LBARD log file can't handle the scenario where time goes backwards.  Need to extend so it treats the time difference as zero if the time is in the past vs what it expects.

**Comment by gardners** [comment]
A pile of time-reversal bugs have been fixed, which is expected to have fixed this problem.  Will create new issue if this turns out not to be the case.
