### ISSUE TITLE
P1:  Enhance traffic prioritisation decision rules for UHF radio traffic

### ISSUE THREAD

**Issue by nanometrenat** [servalproject/lbard#8]
When testing multi-hop and watching the new, more detailed, send-receive info on the diagnostics page of the various Mesh Extenders in our setup, we could see that in a number of cases the required packets weren't getting through in a timely manner.  Data was being transferred at a reasonable rate, but not necessarily of the packets that the Mesh Extender was missing/waiting for.

Need to look at the rules around this again, with a view to streamlining the priority packets.

**Comment by nanometrenat** [comment]
May be related to https://github.com/servalproject/lbard/issues/4, please close if mine's a duplicate....

**Comment by gardners** [comment]
The various efficiency problems that were the underlying cause have been addressed as of commit 93ee0d27a5a09a9ad8fde76eb61f3408268118b9.  While there may be further efficiency improvements possible, they will be subject to separate issues, as bundles now transfer with reasonable efficiency, sufficient for normal use.
